Traceback (most recent call last):
  File "/Users/dorme/.pyenv/versions/3.7.7/lib/python3.7/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/Users/dorme/.pyenv/versions/3.7.7/lib/python3.7/site-packages/nbclient/client.py", line 1087, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/dorme/.pyenv/versions/3.7.7/lib/python3.7/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/dorme/.pyenv/versions/3.7.7/lib/python3.7/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/Users/dorme/.pyenv/versions/3.7.7/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/Users/dorme/.pyenv/versions/3.7.7/lib/python3.7/site-packages/nbclient/client.py", line 541, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/Users/dorme/.pyenv/versions/3.7.7/lib/python3.7/site-packages/nbclient/client.py", line 832, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/dorme/.pyenv/versions/3.7.7/lib/python3.7/site-packages/nbclient/client.py", line 740, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Response plots
response(glm_model, at='median',
         fun=function(x, y, ...) predict(x, y, type='response', ...))
------------------

Error in eval(predvars, data, env): object 'bio4' not found
Traceback:

1. response(glm_model, at = "median", fun = function(x, y, ...) predict(x, 
 .     y, type = "response", ...))
2. response(glm_model, at = "median", fun = function(x, y, ...) predict(x, 
 .     y, type = "response", ...))
3. .local(x, ...)
4. .doResponse(x, var, at, data, cn, expand, rug, ylim, col, lwd, 
 .     add, fun, ...)
5. fun(x, mm)
6. predict(x, y, type = "response", ...)   # at line 3 of file <text>
7. predict(x, y, type = "response", ...)
8. predict.glm(x, y, type = "response", ...)
9. predict.lm(object, newdata, se.fit, scale = 1, type = if (type == 
 .     "link") "response" else type, terms = terms, na.action = na.action)
10. model.frame(Terms, newdata, na.action = na.action, xlev = object$xlevels)
11. model.frame.default(Terms, newdata, na.action = na.action, xlev = object$xlevels)
12. eval(predvars, data, env)
13. eval(predvars, data, env)
ERROR: Error in eval(predvars, data, env): object 'bio4' not found


